---
title: "Catboost"
author: "Great_vishnu"
date: "3/27/2020"
output: html_document
---

```{r}
library(catboost)
library(caret)
library(dplyr)
library(plotly)
```

```{r}
setwd("~/GitHub/PM25/Data")
air <- read.csv("orginal.csv")
str(air)
```

```{r}
set.seed(1234)
ind <- sample(2, nrow(air), replace = T, prob = c(0.8, 0.2))
train <- air[ind==1,]
test <- air[ind==2,]

```

```{r}
y_train <- unlist(train[c('PM25')])
X_train <- train %>% select(-PM25)
y_valid <- unlist(test[c('PM25')])
X_valid <- test %>% select(-PM25)
```

```{r}
train_pool <- catboost.load_pool(data = X_train, label = y_train)
test_pool <- catboost.load_pool(data = X_valid, label = y_valid)
```

```{r}
params <- list(iterations=1500,
               learning_rate=0.01,
               depth=10,
               loss_function='RMSE',
               eval_metric='RMSE',
               random_seed = 55,
               od_type='Iter',
               metric_period = 1,
               od_wait=20,
               use_best_model=TRUE)

```

```{r}
model <- catboost.train(learn_pool = train_pool,params = params)
```
```{r}
catboost.get_model_params(model)
#save(model, file = "catboot.rda")
#predict
y_pred=catboost.predict(model,test_pool)
postResample(y_pred,test$PM25)
```

```{r}
importance <- catboost.get_feature_importance(model, 
                                pool = NULL, 
                                type = 'FeatureImportance',
                                thread_count = 6)


```

```{r}
print(importance)
```

```{r}
plot(importance)
```

